### ISSUE TITLE
Mariela Koutsikaki

### ISSUE THREAD

**Issue by MarielaKoutsikaki** [anamartinovici/githubfun#101]
Hi! I am going through the steps and I would like to be added as a collaborator for the repo.

Thank you :)

**Comment by anamartinovici** [comment]
Hi @MarielaKoutsikaki 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
