### ISSUE TITLE
New Contributor-candidate Niklas

### ISSUE THREAD

**Issue by NiklasR97** [anamartinovici/githubfun#102]
For a GitHubFun workshop, I would like to be added as a contributor. Username: NiklasR97 (EUR  ID: 599050nr)

**Comment by anamartinovici** [comment]
Hi, @NiklasR97 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi, @NiklasR97 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
