### ISSUE TITLE
Request to be added as a collaborator for this repo - Maria Onassis

### ISSUE THREAD

**Issue by mariaonassisrsm** [anamartinovici/githubfun#104]

**Comment by anamartinovici** [comment]
Hi, @mariaonassisrsm 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi, @mariaonassisrsm 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
