### ISSUE TITLE
I would like to be a collatorator for the repo

### ISSUE THREAD

**Issue by RumengLuo** [anamartinovici/githubfun#106]
Write a title and comment to let me know you are going through these steps before a GitHubFun workshop and that you want to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi, @RumengLuo 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

The text you've copy-pasted in your message ("Write a title and comment to let me know you are going through these steps before a GitHubFun workshop and that you want to be added as a collaborator for the repo.") was the instruction that described what *you* had to do. That is, you needed to write a title and comment to let me (Ana) know who you are.

**Comment by anamartinovici** [comment]
Hi, @RumengLuo 

We'll get this fixed, no worries. 

I noticed in the screenshots you've added on Canvas that when you tried to `push` via the RStudio interface, you were asked for your `GitHub` username. This suggests that maybe you didn't go through item 3 of Step 3 (https://github.com/anamartinovici/githubfun/wiki/Step-3:-Install-Git-on-your-device). Can you please do these steps:

- close RStudio
- restart your device
- open RStudio
- open a terminal and type `git config --global --list`

Does the output match the `user.name` and `user.email` you are using for your GitHub account? If `no`, then please make the necessary changes. If `yes`, then:

- delete the local copy of the `githubfun` repository from your device
- clone the `githubfun` repository -> create a file -> stage -> commit -> push

Let me know how these steps go.

**Comment by RumengLuo** [comment]
Okay, I will do them now.

**Comment by RumengLuo** [comment]
I tried all these steps, but still doesn't work.
