### ISSUE TITLE
Request to be added as a collaborator for this repo.

### ISSUE THREAD

**Issue by gekkeseba** [anamartinovici/githubfun#108]
I am going through these steps before a GitHubFun workshop :)

**Comment by anamartinovici** [comment]
Hi, @gekkeseba . Can you please clarify if this is for the ADF course or something else? I cannot tell your name based on the username.

**Comment by gekkeseba** [comment]
This is for the Analyzing Digital Footprints course, my name is; Sebastiaan Hendriks.

**Comment by anamartinovici** [comment]
Thank you.

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
