### ISSUE TITLE
Issue with pushing

### ISSUE THREAD

**Issue by RoelB010** [anamartinovici/githubfun#110]
<img width="647" alt="Schermafbeelding 2022-04-14 om 13 49 58" src="https://user-images.githubusercontent.com/103593065/163384991-084bacec-db65-4de6-b20e-295a3c403a70.png">

Dear Ana, when following the steps provided by you, I fail to upload my txt file.
When pushing the changes, I get asked to enter my github username and password. 
Once I filled those in, I get the following error message (see screenshot).
Do you know how to solve this?

Best,
Roel

**Comment by anamartinovici** [comment]
Hi, @RoelB010 

You need to carefully read the message in the screenshot and then follow the instructions.
As the message says, password authentication is not enough and you need to use a personal access token. The [link included in the message](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/) explains more about how these tokens work and [how to set it up](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). After you fix authentication, you should be able to commit & push. Let me know how it works.
