### ISSUE TITLE
Request to be added as a collaborator for the repo

### ISSUE THREAD

**Issue by ZichengBao** [anamartinovici/githubfun#115]
I want to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi @ZichengBao 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi, @ZichengBao 

Make sure to close the issue if the reason why you've opened it in the first place has been addressed.
