### ISSUE TITLE
Add me as a collaborator

### ISSUE THREAD

**Issue by eberkman3** [anamartinovici/githubfun#117]
Hi Professor,
Could you add me as a collaborator for the repo?
Thanks in advance!
Kind regards,
Emma

**Comment by anamartinovici** [comment]
Hi @eberkman3 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi, @eberkman3 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
