### ISSUE TITLE
Add me as a collaborator 

### ISSUE THREAD

**Issue by yuansiqi47** [anamartinovici/githubfun#118]
Hi Ana,

Could you please add me as a collaborator? Thanks.

Siqi Yuan

**Comment by anamartinovici** [comment]
Hi @yuansiqi47 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @yuansiqi47 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
