### ISSUE TITLE
GitHubFun

### ISSUE THREAD

**Issue by lennonvanlaar** [anamartinovici/githubfun#121]
Dear Ana,

I'm going through these steps before a GitHubFun workshop and that I want to be added as a collaborator for the repository.

Kind regards,
Lennon

**Comment by anamartinovici** [comment]
Hi, @lennonvanlaar 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

The GitHubFun workshop in the ADF course already took place April 11, you can find the recording on Canvas.
