### ISSUE TITLE
Test run

### ISSUE THREAD

**Issue by 477539sl** [anamartinovici/githubfun#122]
Hey there, I am going through these steps before a GitHubFun workshop and I want to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi, @477539sl 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by 477539sl** [comment]
Done
