### ISSUE TITLE
Collaborator for GitHubFun

### ISSUE THREAD

**Issue by HertogJan97** [anamartinovici/githubfun#124]
Hi professor!

A little late, but could you add me as collaborator for the repro please.

Kind regards,
Maurits 569396

**Comment by anamartinovici** [comment]
Hi @HertogJan97 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
