### ISSUE TITLE
trying to contribute via new computer

### ISSUE THREAD

**Issue by jannaoudijn** [anamartinovici/githubfun#125]
Hi Ana, 

As I mentioned I have to follow all the steps again on my new computer :)

**Comment by anamartinovici** [comment]
Hi, @jannaoudijn If you are using the same GitHub account, but on a different computer you don't need to ask to be added as a collaborator again.

I've noticed you could successfully contribute to this repo, which means that you've correctly set up git on your new device. 
I will now close this issue, but you can open it if there's a specific question you have for me.
