### ISSUE TITLE
Collaborator

### ISSUE THREAD

**Issue by seydagk** [anamartinovici/githubfun#127]
request

**Comment by anamartinovici** [comment]
Hi @seydagk 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

For the future, I recommend you introduce yourself, such that repository owners know who you are and why you are requesting something.

**Comment by anamartinovici** [comment]
Hi @seydagk 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
