### ISSUE TITLE
Priscilla Schoots 508895 Digital Footprints

### ISSUE THREAD

**Issue by priscillaschoots** [anamartinovici/githubfun#128]
I'm going through the steps for installing github and I would like to be added as collaborator. Thank you :)

**Comment by anamartinovici** [comment]
Hi @priscillaschoots 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
