### ISSUE TITLE
Nissreen Idriss - Online Consumer Preferences - 561837ni@student.eur.nl

### ISSUE THREAD

**Issue by NissreenIdriss** [anamartinovici/githubfun#137]
I would like to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi @NissreenIdriss 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
