### ISSUE TITLE
Meryem Tanji 521870ma Collaborator Request DFCP

### ISSUE THREAD

**Issue by MeryemTanjiDFCP** [anamartinovici/githubfun#139]
Asking for access to the repository for the Digital Footprints class at RSM.

**Comment by anamartinovici** [comment]
Hi @MeryemTanjiDFCP 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @MeryemTanjiDFCP 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by anamartinovici** [comment]
Hi @MeryemTanjiDFCP 

If I understand correctly, you have managed to fix the issue by following the instructions in step 3 (https://github.com/anamartinovici/githubfun/wiki/Step-3:-Install-Git-on-your-device) and then commit a few days ago:

![image](https://user-images.githubusercontent.com/20222657/169264922-d78b2df5-7058-4651-a87a-1ebd0f14820e.png)

Is there any unresolved issue that I can help you with?

**Comment by MeryemTanjiDFCP** [comment]
Hello @anamartinovici 

I have managed to fix the issue following the steps. There are no unresolved issues at the moment.

**Comment by anamartinovici** [comment]
Hi @MeryemTanjiDFCP . When the reason for why you've opened an issue is resolved, it is good practice that you close it (see my previous messages in this thread). To limit the back-and-forth exchange of messages, I will now close the issue.
