### ISSUE TITLE
Ann-Carolin Schroeter - Please add me as a collaborator

### ISSUE THREAD

**Issue by Ann-Carolin** [anamartinovici/githubfun#14]

**Comment by anamartinovici** [comment]
Hi. I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by anamartinovici** [comment]
@Ann-Carolin I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
