### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by AthinaKas** [anamartinovici/githubfun#140]
I am Athina, I am on your course and I would like to be added as a collaborator in your repo.

**Comment by anamartinovici** [comment]
Hi @AthinaKas 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @AthinaKas 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
