### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Julienhnrt** [anamartinovici/githubfun#144]
Hi, I'm Julien, the research assistant of pr. Lumsdaine!

**Comment by anamartinovici** [comment]
Hi, @Julienhnrt 

It is nice to see you're setting up Git and GitHub. 
I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
