### ISSUE TITLE
Musa Essa - GitHubFun workshop

### ISSUE THREAD

**Issue by Musaessa** [anamartinovici/githubfun#145]
I finished the steps. Please add me as a collaborator.

**Comment by Musaessa** [comment]
Thanks a lot. I keep getting an error saying "fatal: could not create work tree dir 'githubfun': Permission denied". i will try to understand the problem and will close the issue then.

**Comment by anamartinovici** [comment]
Hi @Musaessa 

I can try to help you out. To do that, can you please describe what you are trying to do? That is, what exactly generated this error message.

**Comment by Musaessa** [comment]
Thanks Ana,

I think the problem is in the installation directory. I am not sure if I messed something up when I was installing Git on my PC. I will try tomorrow to repeat the whole process to see if works. In case I am not able to make it happen, I will tell you. Thanks for your availability.

**Comment by anamartinovici** [comment]
Hi @Musaessa 

You've closed the issue, but you did not yet commit & push to the repo. If you're still experiencing issues, you can reopen the issue and let me know how I can help.

**Comment by Musaessa** [comment]
I did not know that we get to do this for issues as well. Can I do that using the browser?

**Comment by anamartinovici** [comment]
> I did not know that we get to do this for issues as well. Can I do that using the browser?

I'm not sure what you mean. Can you please clarify what you want to do using the browser?

**Comment by Musaessa** [comment]
I meant to ask if I can commit and push the closure of the issue using the browser or if I should do it using the R studio. Maybe I misunderstood you

**Comment by anamartinovici** [comment]
Hi @Musaessa What I meant by 

> You've closed the issue, but you did not yet commit & push to the repo

is that you did not yet complete points 5-14 in [Step 4](https://github.com/anamartinovici/githubfun/wiki/Step-4:-Test-if-everything-is-set-up-correctly-by-contributing-to-an-existing-repository). "commit and push" refers to making changes to the files in the repository. Checking if you can commit & push to this repo, where you are a collaborator, allows you to test if you've correctly set up Git and the connection to GitHub on your device.

**Comment by Musaessa** [comment]
Hi @anamartinovici 

Now I get what you mean. I was able to stage, commit and push to the repository. Thank you for the follow up.
