### ISSUE TITLE
Ting - GitHubFun Workshop

### ISSUE THREAD

**Issue by Tingsterr** [anamartinovici/githubfun#146]
Hello Ana,

This is Ting :) I would like to be added as a collaborator for the upcoming PhD workshop!
Hope it is still not too late :p

Thanks in advance!

Best,
Ting

**Comment by anamartinovici** [comment]
Hi, @Tingsterr 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
