### ISSUE TITLE
Hello,I'm testing if everything is set up correctly by contributing to an existing repository

### ISSUE THREAD

**Issue by yunhsu98** [anamartinovici/githubfun#148]

**Comment by yunhsu98** [comment]
Hi Ana, I'm following the course of Analyzing digital footprint. And now I'm following the instruction posted on Canvas.

**Comment by anamartinovici** [comment]
Hi @yunhsu98 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as responsible for this, so you get to practice the feature.
