### ISSUE TITLE
GitHubFun; to be added as a collaborator for the repo

### ISSUE THREAD

**Issue by justinzw2xep** [anamartinovici/githubfun#155]
Thank you in advance.

**Comment by anamartinovici** [comment]
Hi @justinzw2xep 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
