### ISSUE TITLE
Adding as a collaborator

### ISSUE THREAD

**Issue by MyrtheSmith** [anamartinovici/githubfun#163]
I am going through the steps before a GitHubFun workshop and I want to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi @MyrtheSmith 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
