### ISSUE TITLE
ADF: To be added as a collaborator

### ISSUE THREAD

**Issue by Stellansch** [anamartinovici/githubfun#170]
Dear Ana,

Currently going through the ADF steps for the GitHubFun workshop!
I would like to be added as a collaborator for the repo.

 Looking forward to work together.

**Comment by anamartinovici** [comment]
Hi @Stellansch 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
