### ISSUE TITLE
GitHubFun workshop

### ISSUE THREAD

**Issue by Michellebors** [anamartinovici/githubfun#171]
I am going through these steps before a GitHubFun workshop and I would like to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi @Michellebors 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
