### ISSUE TITLE
I would like to be added as a collaborator for the repo

### ISSUE THREAD

**Issue by simonroebers** [anamartinovici/githubfun#172]
As part of the Analyzing Digital Footprints course at the RSM, I would like to confirm that my GitHub setting in RStudio are working correctly. Please add me to the repo, so I can go through all the steps.

**Comment by anamartinovici** [comment]
Hi @simonroebers 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
