### ISSUE TITLE
Im going to the steps for the GitHubFun workshop.

### ISSUE THREAD

**Issue by 478766js** [anamartinovici/githubfun#176]
Hi, I (Jelle van Santen, 478766) want to be added to the repository as a collaborator.

**Comment by anamartinovici** [comment]
Hi @478766js 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by 478766js** [comment]
Hi @anamartinovici , could you please send me another invite? Thank you!

Kind regards, 

Jelle van Santen

**Comment by anamartinovici** [comment]
Hi @478766js Done.

**Comment by anamartinovici** [comment]
Hi @478766js I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
