### ISSUE TITLE
Going through the GitHubFun workshop and I want to be added to the repo

### ISSUE THREAD

**Issue by StenRSM** [anamartinovici/githubfun#177]
Hi Ana,

I am going through the steps for the first deadline and I am wondering if you could add me as a contributor to the repo?

Kind regards,
Sten Willemse - 512275

**Comment by anamartinovici** [comment]
Hi @StenRSM 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @StenRSM 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
