### ISSUE TITLE
I am going through the GitHubFun workshop and I would like be added to the repo

### ISSUE THREAD

**Issue by 623348je** [anamartinovici/githubfun#180]

**Comment by anamartinovici** [comment]
Hi @623348je 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
