### ISSUE TITLE
Currently going through the steps before a GitHubFun workshop + want to be added as a collaborator

### ISSUE THREAD

**Issue by soniamuthi** [anamartinovici/githubfun#181]
Hi,

I am currently following the steps given, and I would like to be added as a collaborator for the repo.

Thanks!
Sonia Muthi (525982sm)
Student @ ADF course

**Comment by anamartinovici** [comment]
Hi @soniamuthi 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
