### ISSUE TITLE
Hi, how are you?

### ISSUE THREAD

**Issue by ao-osiris** [anamartinovici/githubfun#183]
I would love to be added as the collaborator!

**Comment by anamartinovici** [comment]
Hi @ao-osiris 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
