### ISSUE TITLE
Going through the steps

### ISSUE THREAD

**Issue by ReRuh** [anamartinovici/githubfun#184]
Just went through the steps and would like to be added as a collaborator for the repo. 

Thank you very much for your time.

**Comment by anamartinovici** [comment]
Hi @ReRuh 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
