### ISSUE TITLE
Going through the steps

### ISSUE THREAD

**Issue by lennonvanlaar** [anamartinovici/githubfun#186]

**Comment by anamartinovici** [comment]
Hi @lennonvanlaar 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by lennonvanlaar** [comment]
Hi professor, a quick question for the individual assignment. Do I use this https://github.com/Digital-Footprints/adf_indivproject-lennonvanlaar for this year too?
