### ISSUE TITLE
tried to come up with a funny title but failed (and of course request)

### ISSUE THREAD

**Issue by lisaYamazaki** [anamartinovici/githubfun#187]
But anyways i am going through before the workshop. can you add me as a collaborator for the repo?

**Comment by anamartinovici** [comment]
Hi @lisaYamazaki 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
