### ISSUE TITLE
Write a title

### ISSUE THREAD

**Issue by 632427jb** [anamartinovici/githubfun#190]
Leave a comment (I want to be a collaborator for the repo)

**Comment by 632427jb** [comment]
I've been unable to push to the githubfun repo, and I think I know why. I get the following error: _remote: Permission to anamartinovici/githubfun.git denied to Jens-Buurveld._. My git credentials are however not Jens-Buurveld, but 632427jb. I think this is because I also used GitHub Desktop during the Business Analytics Workshop, and that Rstudio therefore still 'thinks' I am Jens-Buurveld, not 632427jb. Do you have any idea on how I could set up my RStudio such that it recognizes my new GitHub account?

**Comment by anamartinovici** [comment]
Hi @632427jb I recommend that you tag me - this increases the probability that I see you message.

First - do you want to use the new account? If yes, then you need to update git credentials stored on your device. This differs a bit between Windows, MacOS, and Linux, so it's best to search for info specific to what you're using. If no, then I can add `Jens-Buurveld` as a collaborator to this repo. It is unclear why you created a new account if you already have been using another one in the past.

**Comment by 632427jb** [comment]
Hi @anamartinovici, I created a new account based on my EUR e-mail as I try to keep school and private accounts separate. But in this specific case it might be easier to assign `Jens-Buurveld` as collaborator. I looked into changing credentials, but figuring all this out would hinder me even more at the moment (and we don't have _that_ much time to begin with).
Thanks for your help so far! I'll use `Jens-Buurveld` from now on, let's hope that the rest of the course goes smoothly :)

**Comment by Jens-Buurveld** [comment]
Leaving a comment with my other account for easier role assignment

**Comment by Jens-Buurveld** [comment]
It worked instantly! Thanks

**Comment by anamartinovici** [comment]
Hi @Jens-Buurveld I've added `Jens-Buurveld` as a collaborator. 

In general I agree that keeping private and work or school accounts separate is a good approach. For this specific usecase, the time needed to set it up such that it works for both accounts doesn't seem to be worth it. 
You might already know this, but just in case: https://docs.github.com/en/enterprise-server@3.4/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/changing-your-primary-email-address This link explains how to add a second email address associated with the GitHub account, and how to remove email addresses you no longer want to use for the GitHub account.
