### ISSUE TITLE
Hi there! Add me as a collaborator for the repo :)

### ISSUE THREAD

**Issue by inemariekeraettig** [anamartinovici/githubfun#193]

**Comment by anamartinovici** [comment]
Hi @inemariekeraettig 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by inemariekeraettig** [comment]
No, I haven't had any difficulties. So I will be closing this issue. Thanks, Ana!
