### ISSUE TITLE
Eid mubarak <3

### ISSUE THREAD

**Issue by SuwarBAM** [anamartinovici/githubfun#199]
Hii i'm going through the steps for githubfun. Could you add me as a collaborator? :)

**Comment by anamartinovici** [comment]
Hi @SuwarBAM 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by SuwarBAM** [comment]
I was successfully able to push to the repository. closing this issue
