### ISSUE TITLE
hi there! Could you please add me as a collaborator? Thank you.

### ISSUE THREAD

**Issue by mariamgasparian** [anamartinovici/githubfun#200]

**Comment by anamartinovici** [comment]
Hi @mariamgasparian 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @mariamgasparian I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by mariamgasparian** [comment]
Closing the issue as I managed to contribute to the repository.
