### ISSUE TITLE
ADF_2023

### ISSUE THREAD

**Issue by jakubu12** [anamartinovici/githubfun#201]
I am writing this comment as a part of the course, and going through the steps specified on Canvas. I would like to become a collaborator. Can you add me? Thank you

**Comment by anamartinovici** [comment]
Hi @jakubu12 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
