### ISSUE TITLE
ADF Going through the steps

### ISSUE THREAD

**Issue by MichelleC1229** [anamartinovici/githubfun#203]
I'm going through the steps specified on Canvas. I would like to become a collaborator. Could you add me? Thank you :)

**Comment by anamartinovici** [comment]
Hi @MichelleC1229 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
