### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by PKahnau** [anamartinovici/githubfun#206]
Hello Mrs. Martinovici

I am going through the steps to join the GitHubFun workshop as a collaborator.

Can you add me?

**Comment by anamartinovici** [comment]
Hi @PKahnau 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
