### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by fauvesmits** [anamartinovici/githubfun#207]
I am going through these steps before a GitHubFun workshop and want to be added as a collaborator for the repo

**Comment by anamartinovici** [comment]
Hi @fauvesmits 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
