### ISSUE TITLE
Request to add me as a collaborator 

### ISSUE THREAD

**Issue by FemkevanSanten** [anamartinovici/githubfun#208]
Hi Ana,

I have been going through these steps before a GitHubFun workshop and want to be added as a collaborator for the repo. 

Kind regards,
Femke van Santen
479804fs

**Comment by anamartinovici** [comment]
Hi @FemkevanSanten 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
