### ISSUE TITLE
Introducing myself

### ISSUE THREAD

**Issue by deboraweel** [anamartinovici/githubfun#215]
Hi, I want to be added as a collaborator. This issue is for the Githubfun workshop.

Debora

**Comment by anamartinovici** [comment]
Hi @deboraweel 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @deboraweel I respond here to your email, as this might be useful also for other students. 

There is a link in the error message:
![image](https://github.com/anamartinovici/githubfun/assets/20222657/a0ff30f3-9b30-415a-bf44-96910e0371f6)
That link explains in more detail what you need to authenticate: https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls In brief, you need to generate a personal access token. See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic for how to generate a token - I recommend going for the classic type and making sure you select at least `repo` as scope. After you generate the token, when you try to push for the first time, RStudio will ask for your username (this is your GitHub username) and password (this is the token, not the GitHub password).

**Comment by anamartinovici** [comment]
Hi @deboraweel I see that in the meantime you've committed to the repository, congratulations! If that works well now, please close this issue by clicking on `Clone with comment` below. Otherwise, let me know what I can help you with.

**Comment by deboraweel** [comment]
> Hi @deboraweel I see that in the meantime you've committed to the repository, congratulations! If that works well now, please close this issue by clicking on `Close` below. Otherwise, let me know what I can help you with.

Oh I'm so sorry! I completely forgot after it worked with the token.
