### ISSUE TITLE
I want to be added as collaborator for the repo

### ISSUE THREAD

**Issue by YvonnevDr** [anamartinovici/githubfun#216]
I am Yvonne van Driel, a student of the elective Digital Footprints for Consumer Preferences and I would like to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi @YvonnevDr 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
