### ISSUE TITLE
I would like to be added as a collaborator

### ISSUE THREAD

**Issue by olivervhh** [anamartinovici/githubfun#219]
Oliver van Hellenberg Hubar - 497064oh

**Comment by AnnaChiaraSaccani** [comment]
Anna Chiara Saccani - 532801as

**Comment by anamartinovici** [comment]
Hi @olivervhh 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
