### ISSUE TITLE
I would like to be added as a collaborator

### ISSUE THREAD

**Issue by kayenetabina** [anamartinovici/githubfun#220]
This is me going through the steps of Assignment 1. Please add me as a collaborator to your repo. Thank you.

**Comment by anamartinovici** [comment]
Hi @kayenetabina 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
