### ISSUE TITLE
I want to be added as a collaborator please

### ISSUE THREAD

**Issue by estherjaspers** [anamartinovici/GitHubFun#225]

**Comment by anamartinovici** [comment]
Hi @estherjaspers 

I have resent the invite. You need to accept it within 2 weeks, otherwise it automatically expires. After you accept the invite, you can try to commit and push to this repo. Let me know if you experience any problem. Otherwise, please close this issue.

**Comment by anamartinovici** [comment]
I'm closing this issue for now. If you try to commit and push and you have questions, you can reopen it.
