### ISSUE TITLE
add as collaborator

### ISSUE THREAD

**Issue by rothl16** [anamartinovici/githubfun#226]
Hi, Im going through the setup check and would ike to be added. Best, Leo

**Comment by anamartinovici** [comment]
Hi @rothl16 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @rothl16 

I see you've committed to the repo in the meantime. If you're still experiencing problems, let me know. Otherwise, please close this issue.
