### ISSUE TITLE
going through the setup steps before a GitHubFun workshop

### ISSUE THREAD

**Issue by thomaskarner** [anamartinovici/githubfun#227]
Hello,
please add me as a collaborator

**Comment by anamartinovici** [comment]
Hi @thomaskarner 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by thomaskarner** [comment]
Hi Ana,

Ok, thank you very much! Looking forward to your workshop on Thursday

 

Best,

Thomas
