### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by BiancaSchuster** [anamartinovici/githubfun#231]
Introducing myself as part of the Version Control: Introduction to Git and Github workshop

**Comment by anamartinovici** [comment]
Hi @BiancaSchuster 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by BiancaSchuster** [comment]
Hi Ana,

The error I get when trying to push the txt file to the repo is 'remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/anamartinovici/githubfun.git/'

**Comment by BiancaSchuster** [comment]
is the issue that the ssh key I have entered into the R github settings is expired?

**Comment by anamartinovici** [comment]
@BiancaSchuster Yes, that could be. You might need to remove the current credentials and then add the updated ones.

Are you using an ssh key or a personal access token?

**Comment by BiancaSchuster** [comment]
I was able to push finally, thanks very much for your help!
