### ISSUE TITLE
Workshop today

### ISSUE THREAD

**Issue by cbenck** [anamartinovici/githubfun#235]

**Comment by anamartinovici** [comment]
Hi @cbenck 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by cbenck** [comment]
I get an error code: >>> /usr/bin/git push origin HEAD:refs/heads/main
remote: Permission to anamartinovici/githubfun.git denied to cbenck.
fatal: unable to access 'https://github.com/anamartinovici/githubfun.git/': The requested URL returned error: 403

(i used a PAT)

**Comment by anamartinovici** [comment]
Hi @cbenck 

I see you've committed to the repo in the meantime. If you're still experiencing problems, let me know. Otherwise, please close this issue.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
