### ISSUE TITLE
Workshop 16.01.24

### ISSUE THREAD

**Issue by evolbert** [anamartinovici/GitHubFun#239]
Hi, I'm Emily Volbert and will attend the workshop next week, 16th of Janurary. I would like to be added as collaborator.

**Comment by anamartinovici** [comment]
Hi @evolbert 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by anamartinovici** [comment]
Hi @evolbert I see you've committed to the repo in the meantime. If you're still experiencing problems, re-open the issue and let me know.
