### ISSUE TITLE
Workshop on 16.01.2024

### ISSUE THREAD

**Issue by sboccadoro** [anamartinovici/GitHubFun#240]
Hallo, I'm Sara Boccadoro and I'll participate to the workshop on the 16.01.2024. I'd like to be added as collaborator

**Comment by anamartinovici** [comment]
Hi @sboccadoro 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by sboccadoro** [comment]
Dear Ms. Martinovici,

Unfortunately I experience issues with Rstudio after downloading Git. I have the most resent version of both R and Rstudio, which work fine. As soon as I download Git, Rstudio stops working, it won't open at all. I tried uninstalling everything and re-installing again but I experience the same issue. I use Windows.

Kind regards,
Sara Boccadoro

**Comment by anamartinovici** [comment]
Hi @sboccadoro That's a very unusual error. Let's take a look and try to fix it. We can meet via Zoom - please use the same meeting as the one for the workshop. I am available now, but if this doesn't work for you then please let me know when is a better time.

**Comment by sboccadoro** [comment]
Thank you for your reply. Unfortunately I don't have time for a zoom meeting today. Would Monday afternoon (any time) work for you?

Best regards,
Sara Boccadoro

**Comment by sboccadoro** [comment]
Thank you very much. I'll try this way, and let you know if it works. Otherwise, I'll see you on Monday at 15.00

Best regards,
Sara Boccadoro

**Comment by sboccadoro** [comment]
Dear Ms Martinovici,

I solved the issue, it had something to do with R version control. Thank you!

Kind regards,
Sara Boccadoro

**Comment by anamartinovici** [comment]
@sboccadoro That's great to hear, thank you for letting me know
