### ISSUE TITLE
Request addition as collaborator

### ISSUE THREAD

**Issue by koch-ju** [anamartinovici/GitHubFun#241]
Dear Ana Martinovici,

Could you please add me as a collaborator for the repo for the workshop on 16.01.?

Best, 
Julia Koch

**Comment by anamartinovici** [comment]
Hi @koch-ju 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by anamartinovici** [comment]
Hi @koch-ju I see you've committed to the repo in the meantime. If you're still experiencing problems, re-open the issue and let me know.
