### ISSUE TITLE
Can I be added as a collaborator for the repo?

### ISSUE THREAD

**Issue by JingJingHe47** [anamartinovici/GitHubFun#247]
I am Jing Jing He and I'm enrolled in the course Analyzing Digital Footprints

**Comment by anamartinovici** [comment]
Hi @JingJingHe47 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
