### ISSUE TITLE
Could you please add me as a collaborator to the repository?

### ISSUE THREAD

**Issue by asiaprzanowska** [anamartinovici/GitHubFun#248]
I'm Joanna Przanowska, and I'm currently enrolled in the course Analyzing Digital Footprints.

**Comment by anamartinovici** [comment]
Hi @asiaprzanowska 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
