### ISSUE TITLE
Request to be added as a collaborator to the repository

### ISSUE THREAD

**Issue by RichardMzk** [anamartinovici/GitHubFun#251]
Hi Ana, 

My name is Richard Miezenbeek and I will be attending the Analysing digital footprints course starting in April 2024. 

Could you please add me as a collaborator to the repository? 

Kind regards,

Richard Miezenbeek

**Comment by anamartinovici** [comment]
Hi @RichardMzk 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
