### ISSUE TITLE
Added as a collaborator for the repo (ADF)

### ISSUE THREAD

**Issue by SharifaOtto** [anamartinovici/GitHubFun#252]
Hi Ana,

My name is Sharifa Otto and I will be attending the ADF course starting in April 2024.

Could you please add me as a collaborator to the repository?

Kind regards,

Sharifa Otto

**Comment by anamartinovici** [comment]
Hi @SharifaOtto 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
