### ISSUE TITLE
494874 Githubfun request

### ISSUE THREAD

**Issue by kisoliver98** [anamartinovici/GitHubFun#253]
My name is Oliver Kamilov (494874). I want to join April 15th workshop.

**Comment by anamartinovici** [comment]
Hi @kisoliver98 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
