### ISSUE TITLE
Githubfun Workshop

### ISSUE THREAD

**Issue by Odvodv** [anamartinovici/GitHubFun#254]
Hi my name is Olivier de Vries I think I am quite late with doing this but I will be in the workshop on 16/04 and would like to be added to the repo

**Comment by anamartinovici** [comment]
Hi @Odvodv 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
