### ISSUE TITLE
Adding as collaborator

### ISSUE THREAD

**Issue by KarolKrawiecki** [anamartinovici/GitHubFun#256]
Hi! My name is Karol, I will be attending this course from 16/04/2024 onwards :)

**Comment by anamartinovici** [comment]
Hi @KarolKrawiecki 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
