### ISSUE TITLE
Adding as a Collaborator

### ISSUE THREAD

**Issue by khanhtrue253** [anamartinovici/GitHubFun#258]
Hi Ana,

Can you add me as a collaborator for this repository? I'm coming from the ADF course at Business Analytics & Management Master 23-24 at Erasmus University Rotterdam, April 24.

**Comment by anamartinovici** [comment]
Hi @khanhtrue253 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
