### ISSUE TITLE
GitHubFun request to be added as collaborator

### ISSUE THREAD

**Issue by SidneyvanWees5** [anamartinovici/GitHubFun#261]
Name: Sidney van Wees
Workshop attended: 16-04-2023.

**Comment by anamartinovici** [comment]
Hi @SidneyvanWees5 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
