### ISSUE TITLE
Access as a collaborator for the repo

### ISSUE THREAD

**Issue by ShiyunnChen** [anamartinovici/GitHubFun#264]
Hi, I'm Shiyun Chen. I am following the 'Analyzing Digital Footprints' elective for BAM this semester, first Workshop on 16/04/2024.

**Comment by anamartinovici** [comment]
Hi @ShiyunnChen 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by ShiyunnChen** [comment]
it works, thank you Ana :)
