### ISSUE TITLE
Request for access to GitHubFun repo

### ISSUE THREAD

**Issue by OrestisOu** [anamartinovici/GitHubFun#265]
Hi, I am currently attending the Analyzing Digital Footprint course. I would kindly ask to be added as a collaborator to the course repo.

Best,
Orestis

**Comment by anamartinovici** [comment]
Hi @OrestisOu 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
