### ISSUE TITLE
Collaborator request

### ISSUE THREAD

**Issue by victoria-derue** [anamartinovici/GitHubFun#266]
Hello, my name is Victoria de Rue. As part of the BAM master's programme, I will take the 'Analysing Digital Footprints' elective, beginning with the first workshop on April 16, 2024.

**Comment by anamartinovici** [comment]
Hi @victoria-derue 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
