### ISSUE TITLE
Collaborator request

### ISSUE THREAD

**Issue by CyrilKleintjes** [anamartinovici/GitHubFun#269]
Hey, My name is Cyril. I will take the 'Analysing Digital Footprints' elective, beginning with the first workshop on April 16, 2024.
Thank you!

**Comment by anamartinovici** [comment]
Hi @CyrilKleintjes 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
