### ISSUE TITLE
Collaborator Request

### ISSUE THREAD

**Issue by thalia0106** [anamartinovici/GitHubFun#270]
Hi, my name is Yuanling Zhu. I'm attending ADF from April 16 and would like to be added to the repo. Thank you!

**Comment by anamartinovici** [comment]
Hi @thalia0106 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
