### ISSUE TITLE
Collaborator request 

### ISSUE THREAD

**Issue by naomige** [anamartinovici/GitHubFun#271]
Hi! Naomi Geelen here

**Comment by anamartinovici** [comment]
Hi @naomige 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by naomige** [comment]
Thank you it worked
