### ISSUE TITLE
Request to be a collaborator

### ISSUE THREAD

**Issue by omaralminawi** [anamartinovici/GitHubFun#277]
Hi Professor, 

My name is Omar Alminawi, I am a student in your Analyzing Digital Footprints class and would like to be added to the repo.

Thanks!

**Comment by anamartinovici** [comment]
Hi @omaralminawi 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
