### ISSUE TITLE
Adam Chan

### ISSUE THREAD

**Issue by AdamChan23074947** [anamartinovici/GitHubFun#279]

**Comment by anamartinovici** [comment]
Hi @AdamChan23074947 

I assume you are following the Analyzing Digital Footprints course.
I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
