### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by michelleclausx** [anamartinovici/githubfun#28]
Dear Ana, 

Please add me as a collaborator for my project: Sentiment Analysis on Twitter data regarding 2020 US Elections

Kind regards, 

Michelle Claus
423820

**Comment by anamartinovici** [comment]
Hi. I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by anamartinovici** [comment]
I am reopening this issue because you didn't commit & push to the repository yet. Close the issue after you commit & push.
