### ISSUE TITLE
Request of new collaborator for the repository: Digital Footprints BME129

### ISSUE THREAD

**Issue by GabrielaGrodecka** [anamartinovici/GitHubFun#282]
Hello, my name is Gabriela Grodecka. I am following the preparation steps from Canvas for the course Digital Footprints BME129 (the closest workshop on 14 May 2024)

**Comment by anamartinovici** [comment]
Hi @GabrielaGrodecka 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
