### ISSUE TITLE
Request to be added as a collaborator

### ISSUE THREAD

**Issue by SuzanJuffer** [anamartinovici/GitHubFun#284]
Dear Ana,

I am currently going through the steps of setting up my GitHub account. I am in your Digital Footprints class, so I am uncertain about when we will have the GitHub workshop.

Kind regards,

Suzan Juffer
568862

**Comment by anamartinovici** [comment]
Hi @SuzanJuffer 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
