### ISSUE TITLE
Request for collaboration

### ISSUE THREAD

**Issue by giozavarise** [anamartinovici/GitHubFun#289]
Hi, I'm Giovanni Zavarise 14 May 2024

**Comment by anamartinovici** [comment]
Hi @giozavarise 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
