### ISSUE TITLE
Request collaborator workshop

### ISSUE THREAD

**Issue by Meghanmun** [anamartinovici/GitHubFun#292]
Hi Ana,
I'm Jeonghyeon(Meghan). Could you please add me as a collaborator?
Thanks in advance!
Jeonghyeon(Meghan)
679786jm

**Comment by anamartinovici** [comment]
Hi @Meghanmun 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
