### ISSUE TITLE
Request new collaborator - workshop 14/05

### ISSUE THREAD

**Issue by janavanderhoek** [anamartinovici/GitHubFun#295]
Hi Ana,

I am taking the course on Digital footprints. Could you add me as a collaborator? 

Thank you in advance.

Kind regards,

Jana van der Hoek

**Comment by anamartinovici** [comment]
Hi @janavanderhoek 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
