### ISSUE TITLE
Getting to know me, Raman

### ISSUE THREAD

**Issue by sraman01** [anamartinovici/GitHubFun#298]
Hereby, I let you know that I am going through these steps before a GitHubFun workshop and that I want to be added as a collaborator for the repo. My name is Raman Singh, and I would like to attend the workshop on 3 June.

**Comment by anamartinovici** [comment]
Hi @sraman01 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

Note that the workshop on version control took place on May 14. You can find the recording on Canvas.
