### ISSUE TITLE
Floris Wevers

### ISSUE THREAD

**Issue by FlorisHW** [anamartinovici/GitHubFun#304]
Dear Professor,

My name is Floris Wevers, and I would like to be added to the repository as a collaborator, as a part of the Digital Footprints course.

**Comment by anamartinovici** [comment]
Hi @FlorisHW 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
