### ISSUE TITLE
kberost - collaborator request

### ISSUE THREAD

**Issue by kberost** [anamartinovici/GitHubFun#310]
Hello Ana Martinovici,

I would like to be added to your repo for the GitHubFun workshop on June 5, 2024. Thanks!

**Comment by anamartinovici** [comment]
Hi @kberost 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by anamartinovici** [comment]
Hi @kberost I notice that you have contributed to the repo, so I am now closing this issue.
