### ISSUE TITLE
Collaborator

### ISSUE THREAD

**Issue by BotondU1910** [anamartinovici/GitHubFun#319]
Hi this is Botond, I have realized while working on the assignments that I am not a collaborator yet.

**Comment by anamartinovici** [comment]
Hi @BotondU1910 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.
