### ISSUE TITLE
Homework!

### ISSUE THREAD

**Issue by GiulioCentorame** [anamartinovici/githubfun#4]
Hi, this is my GitHub profile for the homework! :)

**Comment by anamartinovici** [comment]
Hi Giulio! I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by GiulioCentorame** [comment]
I guess it should be okay now
