### ISSUE TITLE
SIPS Workshop

### ISSUE THREAD

**Issue by sperrig** [anamartinovici/githubfun#43]
Hello :)

I would like to participate in your workshop at SIPS on GitHub and am currently going through the preparatory work.
Could you please add me as a collaborator.

Thank you and have a nice day!

**Comment by anamartinovici** [comment]
Hi, @sperrig 

Welcome to the git side!

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.
