### ISSUE TITLE
please add me as a collaborator

### ISSUE THREAD

**Issue by rkupffer** [anamartinovici/githubfun#44]
hi. Please add me as a collaborator for the githubfun repository.
I am looking forward to the SIPS-workshop. BR Rebekka Kupffer

**Comment by anamartinovici** [comment]
Hi, @rkupffer 

Welcome to the git side!

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.
