### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by Halo2Wappster** [anamartinovici/githubfun#45]
Thank you!

**Comment by anamartinovici** [comment]
Hi, @Halo2Wappster 

I assume that this is SIPS related. Either way, welcome to the git side!

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by Halo2Wappster** [comment]
Thanks for the fast reply!
