### ISSUE TITLE
SIPS 2021 - Please add me as a collaborator

### ISSUE THREAD

**Issue by nathalieyuen** [anamartinovici/githubfun#48]
Hi!  Please add me as a collaborator for the githubfun repo.  Thanks and looking forward to this workshop! #SIPS2021

**Comment by anamartinovici** [comment]
I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by nathalieyuen** [comment]
Thanks for this workshop!
