### ISSUE TITLE
I would like to do the home work as well

### ISSUE THREAD

**Issue by DoesjkaHagenaar** [anamartinovici/githubfun#5]
Thanks in advance!

**Comment by anamartinovici** [comment]
Hi Doesjka! I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by DoesjkaHagenaar** [comment]
Dear Ana,

It all worked well and I closed the issue. Thank you for the nice lecture!

Best,

Doesjka

Op wo 29 apr. 2020 om 12:44 schreef Ana Martinovici <
notifications@github.com>:
