### ISSUE TITLE
Kelly Nguyen

### ISSUE THREAD

**Issue by pnguyen29** [anamartinovici/githubfun#51]
I've followed the steps required before the SIPS workshop.Please add me to the githubfun repo.

**Comment by anamartinovici** [comment]
Hi @pnguyen29 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by anamartinovici** [comment]
Hi @pnguyen29 I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue. It is important to keep GitHub Issues tidy and well organized.
