### ISSUE TITLE
Preparation for SIPS GitFun

### ISSUE THREAD

**Issue by LauraKlatt** [anamartinovici/githubfun#52]
Hi, I would like to be added as collaborator for the githubfunrepo! Sorry for the short notice - I totally understand if this is too spontaneous right before the beginning of the workshop.

Best, 
Laura

**Comment by anamartinovici** [comment]
Hi @LauraKlatt 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.
