### ISSUE TITLE
Preparing for SIPS 2021

### ISSUE THREAD

**Issue by almuclari** [anamartinovici/githubfun#54]
Hello! I'm setting up everything before GitFun starts. I hope it is not too late :)

**Comment by anamartinovici** [comment]
Hi @almuclari 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by almuclari** [comment]
I'm closing this issue. Thank you for the useful workshop! I will definitely use Github for future projects!
