### ISSUE TITLE
sips ws

### ISSUE THREAD

**Issue by thinkaboutthings** [anamartinovici/githubfun#56]
Click “Issues” and then the green “New issue” button. Write a title and comment to let me know you are going through these steps before the SIPS workshop and that you want to be added as a collaborator for the githubfun repo

**Comment by anamartinovici** [comment]
Hi @thinkaboutthings 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by thinkaboutthings** [comment]
yepp,

once again thank you for the session! :)
