### ISSUE TITLE
collab add for homework

### ISSUE THREAD

**Issue by LisaRothmann** [anamartinovici/githubfun#6]
Could I please be added as a collaborator.

**Comment by anamartinovici** [comment]
Hi Lisa! I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by LisaRothmann** [comment]
Hi Ana,

Apologies for only replying now, after a week - I had some research fires
to put out - with lockdown I have not been able to visit our field trials
and it is causing some headaches for me.

Could I please request again to be a collaborator?

Sorry,
Lisa

**Comment by anamartinovici** [comment]
Hi Lisa,

No problem. I've sent the invite to add you as a collaborator.
I hope the research fires remain under control.

Best,
Ana

**Comment by LisaRothmann** [comment]
Thank you so much! and a huge thank you for the workshop!

I am sure they will...

Have a good week further,
Lisa

**Comment by LisaRothmann** [comment]
I did it :) yay!
