### ISSUE TITLE
stats test

### ISSUE THREAD

**Issue by statwood** [anamartinovici/githubfun#60]
i am attempting to complete steps during your SIPS workshop and you currently might be quite preoccupied answering everyone's queries, but if possible i'd like to be added as a collaborator for the githubfunrepo. Thank you!

**Comment by anamartinovici** [comment]
Hi @statwood 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.
