### ISSUE TITLE
Hi, I'm joining the workshop at SIPS :-)

### ISSUE THREAD

**Issue by AnneGaertner202** [anamartinovici/githubfun#62]

**Comment by anamartinovici** [comment]
Hi @AnneGaertner202 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by AnneGaertner202** [comment]
Thank you very much for all of this! It really helped getting in touch with Github!
