### ISSUE TITLE
SIPS WS

### ISSUE THREAD

**Issue by JeanMoneger** [anamartinovici/githubfun#63]
Hey! Thanks for the workshop :)

**Comment by anamartinovici** [comment]
Hi @JeanMoneger 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

You're welcome :) I'm happy to see people excited about using git and GitHub.

**Comment by JeanMoneger** [comment]
Thanks again :)
