### ISSUE TITLE
Collaborator - better late than never

### ISSUE THREAD

**Issue by janakathako** [anamartinovici/githubfun#78]

**Comment by anamartinovici** [comment]
Hi @janakathako 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

I do agree on better late than never :)

**Comment by anamartinovici** [comment]
No reply - I am now closing this issue myself. If you have questions, you can reopen the issue or open a new issue.
