### ISSUE TITLE
Homework please! :)

### ISSUE THREAD

**Issue by suusgerritsen** [anamartinovici/githubfun#8]

**Comment by anamartinovici** [comment]
Hi! I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, can you please close this issue? I have assigned you as 'responsible' for this, just to practice the feature.

**Comment by suusgerritsen** [comment]
Thanks! It worked! Thanks for the interesting webinar! I really liked the interactive elements, it will really help to actually start using it, I hope... :)
