### ISSUE TITLE
workshop april 7

### ISSUE THREAD

**Issue by VerheyenS** [anamartinovici/githubfun#84]
Dear Ana,

I'm going through the preparatory steps for tomorrow's workshop. Please add me as a collaborator.

Kind regards,
Steven

**Comment by anamartinovici** [comment]
Hi, @VerheyenS 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
