### ISSUE TITLE
Git introduction

### ISSUE THREAD

**Issue by Tsjitsjikow** [anamartinovici/githubfun#86]
Hi Ana, this is Leo!

Can I be added as collaborator?

Looking forward to the workshop and finally implementing version control for my R/Python projects.

**Comment by anamartinovici** [comment]
Hi, @Tsjitsjikow 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by Tsjitsjikow** [comment]
Thanks again for the workshop Ana!
