### ISSUE TITLE
Please add me as collaborator prior to the workshop

### ISSUE THREAD

**Issue by SaraHogye** [anamartinovici/githubfun#91]
I am currently going through the set up steps prior to the Github workshop. Could you please add me as a collaborator if that is still possible prior to the workshop? 

Best, Sari

**Comment by anamartinovici** [comment]
Hi, @SaraHogye 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by SaraHogye** [comment]
Thank you, @anamartinovici for your help! 
It all works fine.
