### ISSUE TITLE
add me

### ISSUE THREAD

**Issue by marloeshagens** [anamartinovici/githubfun#92]
For the Github workshop

**Comment by anamartinovici** [comment]
Hi, @marloeshagens 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
This issue is stale because the OP did not reply. If needed, the OP can re-open the issue.
