### ISSUE TITLE
Please add me:)

### ISSUE THREAD

**Issue by Xiaohui-bam** [anamartinovici/githubfun#94]
Dear Professor,

Please add me as the collaborator for the repo.

Best,
Xiaohui Lu

**Comment by Xiaohui-bam** [comment]
[BM25BAM]

**Comment by anamartinovici** [comment]
Hi, @Xiaohui-bam 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
