### ISSUE TITLE
GitHubFun Workshop Request 

### ISSUE THREAD

**Issue by Niko-1003** [anamartinovici/githubfun#99]
Hi 

I'm currently going through the steps that will (hopefully) lead to a functioning work environment for our class. Would you please add me as a collaborator for the repo? Thank you :)

**Comment by anamartinovici** [comment]
Hi, @Niko-1003 

I have added you as a collaborator. You need to accept the invite and then you should be able to push to this repository.
If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.
